### ISSUE TITLE
[Feature] Support using code-generator to generate client

### ISSUE THREAD

**Issue by majian159** [oam-dev/kubevela-core-api#2]

**Comment by wonderflow** [comment]
@majian159  Please note this repo is automatically updated by script. \cc @yangsoon

**Comment by yangsoon** [comment]
Hi, @majian159. the code of repo **kubevela-core-api** was generated from `kubevela/apis`. Every release of `kubevela` will trigger the `github-action `to sync the code. you can refer to this PR https://github.com/oam-dev/kubevela/pull/1523. We suggest you could also generated the code of client by script.
